# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-03 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='Images',
        ),
    ]
