# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0003_images_uploader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='remark',
            new_name='caption',
        ),
    ]
