# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0005_auto_20180904_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='file',
            field=models.ImageField(upload_to=b''),
        ),
    ]
