# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0006_auto_20180904_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='file',
            new_name='art',
        ),
    ]
